name: Memo Cata Build
on: 
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      ghc-version:
        required: false
        type: string
        default: 8.10.7 # =18.25
jobs:
  linting-haskell:
    name: Linting Haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check stylish-haskell and hlint
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s ${{ inputs.project }}
          sh ./.github/stylish-haskell-0.13.0.0.sh | sh -s $(find ./${{ inputs.project }} -type f -name "*.hs" ! -path "*.stack-work*" ! -path "*executable*") -i
          if [ -z "$(git status --porcelain)" ]; then
              echo "No style errors detected."
          else
              echo "Style errors detected:"
              git --no-pager diff
              exit 1
          fi

  run-haskell:
    name: Build Haskell & Run Tests
    needs: linting-haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ${{ inputs.project }}/.stack-work
          key: ${{ runner.os }}-${{ hashFiles('${{ inputs.project }}/stack.yaml.lock', '${{ inputs.project }}/package.yaml') }}
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          ghc-version: ${{ inputs.ghc-version }}
          cabal-version: "latest"
          stack-version: "latest"
      - name: Stack build
        working-directory: ./${{ inputs.project }}
        run: stack build
      - name: Stack test
        working-directory: ./${{ inputs.project }}
        run: stack test
