name: Memo Cata GitHub Actions
on: [push]
jobs:
  linting-haskell:
    name: Linting Haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check stylish-haskell and hlint
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s memo-cata-prototype
          curl -sSL https://raw.github.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s $(find . -type f -name "*.hs" ! -path "*.stack-work*" ! -path "*executable*") -i
          if [ -z "$(git status --porcelain)" ]; then
              echo "No style errors detected."
          else
              echo "Style errors detected:"
              git --no-pager diff
              exit 1
          fi

  run-haskell:
    name: Build Haskell & Run Tests
    needs: linting-haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            prototype/.stack-work
          key: ${{ runner.os }}-${{ hashFiles('prototype/stack.yaml.lock', 'prototype/package.yaml') }}
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          ghc-version: 8.10.7 # =18.25
          cabal-version: "latest"
          stack-version: "latest"
      - name: Stack build
        working-directory: ./prototype
        run: stack build
      - name: Stack test
        working-directory: ./prototype
        run: stack test
