name: Memo Cata Regular
on:
  push:
    paths: 
      - '.github/**'
      - 'regular/**'
jobs:
  call-workflow:
    uses: ./.github/workflows/build.yaml
    with:
      project: regular
      ghc-version: 7.10.3